### ISSUE TITLE
Doesn't seem to be adhering to kubeadm yaml requirements

### ISSUE THREAD

**Issue by perezjasonr** [platform9/nodeadm#102]
Hello, I tried to run nodeadm init using a config file based off of the main readme.md from the documentation and I get:

```
INFO[0025] stderr: invalid configuration: kind and apiVersion is mandatory information that needs to be specified in all YAML documents
FATA[0025] failed to run "/opt/bin/kubeadm init --ignore-preflight-errors=all --config=/tmp/kubeadm.yaml": command "/opt/bin/kubeadm init --ignore-preflight-errors=all --config=/tmp/kubeadm.yaml" failed: exit status 3
```

since its saying it needs to be specified in **all** YAML documents and I'm only providing the one cfg to nodeadm I'm guessing this has something to do with how nodeadm is preparing configs for kubeadm, correct me if I'm wrong or if I did something wrong.

here is the config I tried to pass along, its essentially the provided one in the walkthrough:

```
networking:
    podSubnet: 192.168.0.0/16
    serviceSubnet: 192.169.0.0/24
    dnsDomain: k8s.local
masterConfiguration:
  api:
    advertiseAddress: 172.30.28.14
    bindPort: 443
  apiServerCertSANs:
  - 172.30.28.14
  etcd:
    caFile: /etc/etcd/pki/ca.crt
    certFile: /etc/etcd/pki/apiserver-etcd-client.crt
    keyFile: /etc/etcd/pki/apiserver-etcd-client.key
    endpoints:
    - https://127.0.0.1:2379
  networking:
    podSubnet: 192.168.0.0/16
    serviceSubnet: 192.169.0.0/24
```

note that I appended the last couple lines:
networking:
    podSubnet: 192.168.0.0/16
    serviceSubnet: 192.169.0.0/24

because it complains about not having it defined there for flannel:

```
ERRO[0000] Failed to validate configuration:
ERRO[0000] 0: masterConfiguration.networking.podSubnet must be defined for flannel to work
```

so that one section differs from whats in the main readme.md, im not sure if its actually even using the first three lines for anything since its asking for podSubnet which I thought was provided at the top.
